// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igksahmwobdmpvgogere.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlna3NhaG13b2JkbXB2Z29nZXJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0MDEyMjIsImV4cCI6MjA1Mjk3NzIyMn0.npUn5I164Py3ggmwbgkGt_wc47Ih0YJtg032jgx0nSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);